### PR TITLE
Add a decentralized pyquaticus bridge

### PR DESCRIPTION
**Pull request by makaimann**
This PR implements a new version of the Pyquaticus->MOOS bridge for deploying Pyquaticus policies in MOOS-IvP.

There are several changes included:
* Rather than connect to every node (all agents and shoreside), only connects to the node for the agent you're running
* Allows running a single agent in a separate Docker container without connecting to all nodes (more efficient)
* Refactors so that it uses code common to both Pyquaticus itself and the bridge environment to go from a state representation to normalized observations and interpret actions

The refactoring made minor changes to some underlying data structures that touched a lot of code, but was simple conceptually. For example, the `self.players` variable used to be a list but is now a dictionary, because MOOS agent ids are strings not integers.

### CODE REVIEW

**Comment by makaimann** [comment]
Hey @PatP15 and @ptcrowley, I have a working version of the new bridge file. See above for a summary of the changes.

I know this is a really big PR -- sorry. Feel free to check in as much or as little detail as you'd like. It's not my normal style, but I didn't want to have intermediate PRs with things in a broken state. This update required some refactoring that was conceptually simple but touched a lot of code.

# Requested Test
If you only do one thing, please just check that it runs for you. First, use an env for both pyquaticus and MOOS. Then there's two steps: 
1. start `demo_1v1.sh`
2. in a separate terminal run `python ./test/pyquaticus_moos_bridge_rand_test.py` which should send random actions to the red agent

Note that the original pyquaticus bridge (renamed to `pyquaticus_team_env_bridge` is still in there). However, it doesn't actually work with the saved policies because the observation space changed with the `agent_home_distance/bearing` fields for the return to home feature. I was thinking I'd clean that up or possibly even remove it entirely in a separate PR. Let me know what you think.

**Comment by makaimann** [comment]
@PatP15, the main other thing to check is this commit: https://github.com/mit-ll-trusted-autonomy/pyquaticus/pull/10/commits/287d4f666249676211bfde3d17d657ef0db1f6a3. That's where I merged your changes into this branch and I tweaked a couple things.

**Comment by PatP15** [comment]
> Hey @PatP15 and @ptcrowley, I have a working version of the new bridge file. See above for a summary of the changes.
> 
> I know this is a really big PR -- sorry. Feel free to check in as much or as little detail as you'd like. It's not my normal style, but I didn't want to have intermediate PRs with things in a broken state. This update required some refactoring that was conceptually simple but touched a lot of code.
> 
> # Requested Test
> If you only do one thing, please just check that it runs for you. First, use an env for both pyquaticus and MOOS. Then there's two steps:
> 
> 1. start `demo_1v1.sh`
> 2. in a separate terminal run `python ./test/pyquaticus_moos_bridge_rand_test.py` which should send random actions to the red agent
> 
> Note that the original pyquaticus bridge (renamed to `pyquaticus_team_env_bridge` is still in there). However, it doesn't actually work with the saved policies because the observation space changed with the `agent_home_distance/bearing` fields for the return to home feature. I was thinking I'd clean that up or possibly even remove it entirely in a separate PR. Let me know what you think.


It works good on my end! The only thing I am encountering so far is a warning "Warning: getting no tag cooldown information!". Is it not getting an observation from MOOS? One thing I also had to do was pip install pymoos so we can add that to the setup-conda-env.sh script and the docker.

I agree with removing the agent_home_distance/bearing fields. I added them for the strawmen agents to return home, but since we added the drive-to-home feature, they're unnecessary. Let me know when you update the observations so I can train some more agents!

Last thing, just to make sure I'm understanding correctly, this is supposed to replace the pyquaticus_bridge that you made some time ago right? So what I need to do is update to corresponding scripts in the docker to use this and replace the old pyquaticus_bridge stuff/ As soon as we merge this, I can make another PR that updates the scripts/models in the docker.

**Comment by makaimann** [comment]
Great! Thanks for trying this out.

1. yeah those warnings are for me to remember to update. Mike is adding a new message to include tag cooldown info but we don’t have that yet
2. Sounds good, I’ll make a new PR today!
3. And yes, your understanding on using this new bridge instead is correct. Thanks!

**Comment by makaimann** [comment]
I'm marking this as `do not merge` for now. I'd like to get https://github.com/mit-ll-trusted-autonomy/pyquaticus/pull/9 merged first and I'll handle the conflicts in this branch.

**Pull request merged**
